name: Build
on:
  workflow_call:

jobs:

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: Run :pdf:androidApp:bundleRelease
        run: ./gradlew :pdf:androidApp:assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: androidApp-release.apk
          path: pdf/androidApp/build/outputs/apk/release

  build-desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Create local tag
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "${{ needs.input-check.outputs.validated_tag }}" "$GITHUB_SHA"
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: Build jar
        run: ./gradlew :pdf:desktopApp:jvmJar
      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@9e90ce7c2a4356c99d68c63f41e4bc497da279c8 # v22.0
        env:
          OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          CONVEYOR_PASSPHRASE: ${{ secrets.CONVEYOR_PASSPHRASE  }}
        with:
          command: -f ci.conveyor.conf make site
          extra_flags: '--passphrase=env:CONVEYOR_PASSPHRASE'
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
      - name: Upload Desktop Binaries
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: conveyor-output
          path: output/*

  check-build:
    name: All Build Passed
    runs-on: ubuntu-latest
    needs: [ build-android, build-desktop ]
    steps:
      - name: Confirm All Build Jobs Succeeded
        run: echo "✅ All build jobs (Android, Windows, macOS, Linux) completed successfully."
