name: Build
on:
  workflow_call:

jobs:

  android-build:
    uses: SorrowBlue/github-actions/.github/workflows/android-build.yml@main
    secrets: inherit
    with:
      environment: android-debug
      task: :pdf:androidApp:assembleRelease :pdf:androidApp:bundleRelease
      output-path: pdf/androidApp/build/outputs/

  conveyor-build:
    uses: SorrowBlue/github-actions/.github/workflows/conveyor-build.yml@main
    secrets: inherit
    with:
      matrix-json: .github/conveyor-build-matrix.json
      task: :pdf:desktopApp:jvmJar :pdf:desktopApp:printConveyorConfig :pdf:desktopApp:writeConveyorConfig :pdf:desktopApp:copyConveyorInputs
      environment: conveyor
