name: Internal App Sharing

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:

  build-upload:
    uses: SorrowBlue/github-actions/.github/workflows/android-publish.yml@main
    secrets: inherit
    with:
      environment: android-release
      fetch-depth: 0
      task: bundleInternal
      package-name: com.sorrowblue.comicviewer.plugin.pdf
      release-files: pdf/androidApp/build/outputs/bundle/release/androidApp-release.aab
      tracks: internalsharing
      mapping-file: pdf/androidApp/build/outputs/mapping/release/mapping.txt
      debug-symbols: pdf/androidApp/build/intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib

  notify:
    needs: build-upload
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708 # v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: ":sparkles: Uploaded to internal app share."
          description: |
            Click [here](${{ needs.build-upload.outputs.internalSharingDownloadUrl }}) to download!
          color: 0xff91a4
