name: Internal App Sharing

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    environment: android-release
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: Decode android keystore file
        id: android_keystore
        uses: timheuer/base64-to-file@dfa5a5dd38803cb4f5c3a081eeb28e8362d43e9c # v2
        with:
          fileName: 'android_keystore.jks'
          encodedString: ${{ secrets.ANDROID_STORE_FILE_BASE64 }}
      - name: Run :pdf:androidApp:bundleRelease
        run: ./gradlew :pdf:androidApp:bundleRelease
        env:
          ORG_GRADLE_PROJECT_androidSigningReleaseStoreFile: ${{ steps.android_keystore.outputs.filePath }}
          ORG_GRADLE_PROJECT_androidSigningReleaseStorePassword: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ORG_GRADLE_PROJECT_androidSigningReleaseKeyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          ORG_GRADLE_PROJECT_androidSigningReleaseKeyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
      - name: Upload AAB to Internal App Sharing (Attempt)
        id: upload
        uses: r0adkll/upload-google-play@e738b9dd8f2476ea806d921b64aacd24f34515a5 # v1
        with:
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
          packageName: com.sorrowblue.comicviewer.plugin.pdf
          releaseFiles: pdf/androidApp/build/outputs/bundle/release/androidApp-release.aab
          tracks: internalsharing
          mappingFile: pdf/androidApp/build/outputs/mapping/release/mapping.txt
          debugSymbols: pdf/androidApp/build/intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib

      - name: Notify Discord
        uses: sarisia/actions-status-discord@eb045afee445dc055c18d3d90bd0f244fd062708 # v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: ":sparkles: Uploaded to internal app share."
          description: |
            Click [here](${{ steps.upload.outputs.internalSharingDownloadUrl }}) to download!
          color: 0xff91a4
