name: Publish conveyor
on:
  workflow_dispatch:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: Run :pdf:desktopApp:jvmJar
        run: ./gradlew :pdf:desktopApp:jvmJar
      - name: Decode WINDOWS_CER
        id: windows_cer
        uses: timheuer/base64-to-file@v2
        with:
          fileName: 'windows.cer'
          encodedString: ${{ secrets.WINDOWS_CER }}
      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v22.0
        env:
          OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          CONVEYOR_PASSPHRASE: ${{ secrets.CONVEYOR_PASSPHRASE  }}
          WINDOWS_CER: ${{ steps.windows_cer.outputs.filePath }}
        with:
          command: -f ci.conveyor.conf make site
          extra_flags: '--passphrase=env:CONVEYOR_PASSPHRASE'
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1

      - name: Prepare files for deployment
        run: |
          mkdir -p site
          cp output/download.html site/
          cp output/icon.png site/
          cp -r docs site/
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./site
          destination: ./_site
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v5
        with:
          path: './_site'

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
