name: Update Licenses
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  update-licenses:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup JDK and Gradle
        uses: ./.github/actions/setup-java-gradle
      - name: 🤖 ExportLibraryDefinitions for android
        run: ./gradlew :pdf:androidApp:exportLibraryDefinitions --no-configure-on-demand
        env:
          ORG_GRADLE_PROJECT_githubApiToken: ${{ secrets.GITHUB_TOKEN }}
      - name: 🖥️ ExportLibraryDefinitions for jvm
        run: ./gradlew :pdf:desktopApp:exportLibraryDefinitions --no-configure-on-demand
        env:
          ORG_GRADLE_PROJECT_githubApiToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          token: ${{ secrets.PAT }}
          title: 'Update aboutlibraries.json'
          body: 'This PR updates the aboutlibraries.json'
          base: main
          branch: chore/update-licenses
          assignees: 'SorrowBlue'
          reviewers: 'Copilot'
          labels: ':robot:create-pull-request'
          commit-message: 'Update aboutlibraries.json'

      - name: Enable Auto Merge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d # v3
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
